name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: matrix.platform == 'arm64'
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Find and build Docker images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
        run: |
          # Преобразуем имя пользователя GitHub в нижний регистр
          GITHUB_REPOSITORY_LOWER=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          # Используем команду find для поиска всех подкаталогов с Dockerfile
          DOCKERFILES=$(find . -name Dockerfile -exec dirname {} \;)
          for dir in $DOCKERFILES; do
            # Получаем имя папки из пути и форматируем его для использования в теге Docker
            folder_name=$(basename $dir)
            folder_name_lc=$(echo "${folder_name}" | tr '[:upper:]' '[:lower:]' | tr -cd '[[:alnum:]]_-')
            # Строим имя образа, используя имя папки и динамически определенное имя репозитория
            image_name="ghcr.io/${GITHUB_REPOSITORY_LOWER}:${folder_name_lc}"
            echo "Building image $image_name in directory $dir"
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
            docker build -t $image_name $dir
            docker push $image_name
          done

